# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c05148ca9bc1313c9cd06cae9da340adf9cf99a905d15e1c71bf4ce6fd7a1204496215677038f8b24a255b26600cf46b5ee0fccf067105ab3ab25488a6a8c8b4

test:
  secret_key_base: d2d24bd43d77ee7b958fdd3af8aaaa36ad7aa5292883699c70389e76d7025c22bb81800cfcf948a0bce118f960117aa4c4ea8141454348384a936eaa4a3c513e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
